name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Environment
      # Remove the last two lines of this step after our test suite is compatible with selenium 3.
      run: |
        export DISPLAY=:99.0
        sudo apt-get install xvfb
        sh install_test_deps.sh
        pip uninstall -y selenium
        pip install selenium==2.53.6
    - name: Install Dependencies
      run: |
        python setup.py sdist
        pip install dist/xblock-drag-and-drop-v2-*.tar.gz
        pip install pylint
    - name: Setup Firefox
      uses: browser-actions/setup-firefox@latest
      with:
        firefox-version: '46.0'

    - name: Run tests
      run: |
        pycodestyle drag_and_drop_v2 tests --max-line-length=120
        pylint drag_and_drop_v2
        pylint tests
        python run_tests.py
